# Generated by Django 4.1.7 on 2023-03-11 21:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="coupon_code",
            field=models.CharField(max_length=8, null=True, unique=True),
        ),
    ]
