# Generated by Django 4.1.7 on 2023-03-31 22:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0002_remove_product_ratings_alter_productreview_ratings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productreview",
            name="ratings",
            field=models.IntegerField(
                choices=[
                    (1, "1 star"),
                    (2, "2 stars"),
                    (3, "3 stars"),
                    (4, "4 stars"),
                    (5, "5 stars"),
                ],
                null=True,
            ),
        ),
    ]
