# Generated by Django 4.1.7 on 2023-03-26 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("store", "0002_cart_coupon_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="gender",
            field=models.CharField(
                choices=[("A", "All"), ("M", "Male"), ("F", "Female")],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="customer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
