# Generated by Django 4.1.7 on 2023-03-31 22:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("store", "0003_alter_productreview_ratings"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="customers",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
