# Generated by Django 4.1.7 on 2023-05-21 16:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("store", "0003_remove_cartitem_cart_remove_cartitem_product_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="customers",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
