# Generated by Django 4.1.7 on 2023-03-26 11:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0003_category_gender_order_customer"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="address",
            options={"verbose_name_plural": "Addresses"},
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
        migrations.AlterModelOptions(
            name="country",
            options={"verbose_name_plural": "Countries"},
        ),
        migrations.AlterField(
            model_name="address",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 3, 26, 11, 3, 14, 847617, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="cart",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 3, 26, 11, 3, 14, 847617, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 3, 26, 11, 3, 14, 847617, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 3, 26, 11, 3, 14, 847617, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="colour",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 3, 26, 11, 3, 14, 847617, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="colour",
            name="updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="country",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 3, 26, 11, 3, 14, 847617, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="country",
            name="updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="couponcode",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 3, 26, 11, 3, 14, 847617, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="couponcode",
            name="updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="favoriteproduct",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 3, 26, 11, 3, 14, 847617, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="favoriteproduct",
            name="updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="itemlocation",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 3, 26, 11, 3, 14, 847617, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="itemlocation",
            name="updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="notification",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 3, 26, 11, 3, 14, 847617, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 3, 26, 11, 3, 14, 847617, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 3, 26, 11, 3, 14, 847617, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 3, 26, 11, 3, 14, 847617, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="productreview",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 3, 26, 11, 3, 14, 847617, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="productreview",
            name="updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="size",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 3, 26, 11, 3, 14, 847617, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="size",
            name="updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="sliderimage",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 3, 26, 11, 3, 14, 847617, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="sliderimage",
            name="updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
