# Generated by Django 4.1.7 on 2023-05-21 18:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0004_alter_notification_customers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="transaction_ref",
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
    ]
