# Generated by Django 4.1.7 on 2023-06-01 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0005_alter_order_transaction_ref"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productreviewimage",
            name="product_review",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="store.productreview",
            ),
        ),
    ]
