# Generated by Django 4.1.7 on 2023-04-04 23:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0005_remove_cartitem_unique_cart_product_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="favoriteproduct",
            name="unique_customer_product",
        ),
    ]
