# Generated by Django 4.1.7 on 2023-04-07 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0007_alter_address_id_alter_cart_id_alter_cartitem_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="colour",
        ),
        migrations.RemoveField(
            model_name="product",
            name="size",
        ),
        migrations.AlterField(
            model_name="colour",
            name="name",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name="SizeInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(blank=True, default=0)),
                (
                    "extra_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="size_inventory",
                        to="store.product",
                    ),
                ),
                (
                    "size",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_size",
                        to="store.size",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Product Size & Inventories",
            },
        ),
        migrations.CreateModel(
            name="ColorInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(blank=True, default=0)),
                (
                    "extra_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "colour",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_color",
                        to="store.colour",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="color_inventory",
                        to="store.product",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Product Color & Inventories",
            },
        ),
    ]
