# Generated by Django 4.1.7 on 2023-04-09 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0008_remove_product_colour_remove_product_size_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductColorSizeInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(blank=True, default=0)),
                (
                    "extra_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Product Color, Size & Inventories",
            },
        ),
        migrations.RemoveField(
            model_name="colorinventory",
            name="colour",
        ),
        migrations.RemoveField(
            model_name="colorinventory",
            name="product",
        ),
        migrations.RemoveField(
            model_name="sizeinventory",
            name="product",
        ),
        migrations.RemoveField(
            model_name="sizeinventory",
            name="size",
        ),
        migrations.AddConstraint(
            model_name="cartitem",
            constraint=models.UniqueConstraint(
                fields=("cart", "product"), name="unique_cart_product"
            ),
        ),
        migrations.DeleteModel(
            name="ColorInventory",
        ),
        migrations.DeleteModel(
            name="SizeInventory",
        ),
        migrations.AddField(
            model_name="productcolorsizeinventory",
            name="colour",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_color",
                to="store.colour",
            ),
        ),
        migrations.AddField(
            model_name="productcolorsizeinventory",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_color_size_inventory",
                to="store.product",
            ),
        ),
        migrations.AddField(
            model_name="productcolorsizeinventory",
            name="size",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_size",
                to="store.size",
            ),
        ),
    ]
