# Generated by Django 4.1.7 on 2023-04-10 01:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0009_productcolorsizeinventory_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="inventory",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
