# Generated by Django 4.1.7 on 2023-04-10 02:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0010_alter_product_inventory"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="inventory",
        ),
    ]
