# Generated by Django 4.1.7 on 2023-04-10 20:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0012_colorinventory_sizeinventory_product_inventory_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ColorInventory",
            new_name="ColourInventory",
        ),
        migrations.RenameField(
            model_name="colourinventory",
            old_name="color",
            new_name="colour",
        ),
    ]
