# Generated by Django 4.1.7 on 2023-04-17 23:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0013_rename_colorinventory_colourinventory_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="address",
            options={"ordering": ("-created",), "verbose_name_plural": "Addresses"},
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ("-created",), "verbose_name_plural": "Categories"},
        ),
        migrations.AlterModelOptions(
            name="colour",
            options={"ordering": ("-created",)},
        ),
        migrations.AlterModelOptions(
            name="country",
            options={"ordering": ("-created",), "verbose_name_plural": "Countries"},
        ),
        migrations.AlterModelOptions(
            name="couponcode",
            options={"ordering": ("-created",)},
        ),
        migrations.AlterModelOptions(
            name="favoriteproduct",
            options={"ordering": ("-created",)},
        ),
        migrations.AlterModelOptions(
            name="notification",
            options={"ordering": ("-created",)},
        ),
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ("-created",)},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ("-created",)},
        ),
        migrations.AlterModelOptions(
            name="productreview",
            options={"ordering": ("-created",)},
        ),
        migrations.AlterModelOptions(
            name="size",
            options={"ordering": ("-created",)},
        ),
        migrations.AlterModelOptions(
            name="sliderimage",
            options={"ordering": ("-created",)},
        ),
        migrations.AddField(
            model_name="order",
            name="total_price",
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="gender",
            field=models.CharField(
                choices=[("A", "All"), ("K", "Kids"), ("M", "Male"), ("F", "Female")],
                max_length=1,
                null=True,
            ),
        ),
    ]
