# Generated by Django 4.1.7 on 2023-04-18 00:03

from django.db import migrations, models
import secrets


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0014_alter_address_options_alter_category_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="transaction_ref",
            field=models.CharField(
                default=secrets.token_urlsafe, max_length=12, unique=True
            ),
        ),
    ]
