# Generated by Django 4.1.7 on 2023-04-18 20:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0015_alter_order_transaction_ref"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productimage",
            old_name="image",
            new_name="_image",
        ),
        migrations.RenameField(
            model_name="productreviewimage",
            old_name="image",
            new_name="_image",
        ),
        migrations.RenameField(
            model_name="sliderimage",
            old_name="image",
            new_name="_image",
        ),
    ]
