# Generated by Django 4.1.7 on 2023-04-18 20:16

from django.db import migrations, models
import store.models
import store.validators


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0016_rename_image_productimage__image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="_image",
            field=models.ImageField(
                upload_to=store.models.upload_path,
                validators=[store.validators.validate_image_size],
            ),
        ),
        migrations.AlterField(
            model_name="productreviewimage",
            name="_image",
            field=models.ImageField(
                upload_to=store.models.upload_path,
                validators=[store.validators.validate_image_size],
            ),
        ),
        migrations.AlterField(
            model_name="sliderimage",
            name="_image",
            field=models.ImageField(
                upload_to=store.models.upload_path,
                validators=[store.validators.validate_image_size],
            ),
        ),
    ]
