# Generated by Django 4.1.7 on 2023-04-19 20:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0017_alter_productimage__image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="colourinventory",
            name="extra_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=6, null=True
            ),
        ),
        migrations.AlterField(
            model_name="sizeinventory",
            name="extra_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=6, null=True
            ),
        ),
    ]
