# Generated by Django 4.1.7 on 2023-04-22 22:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import store.validators


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("store", "0020_alter_colourinventory_colour_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="customer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="carts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="_image",
            field=models.ImageField(
                upload_to="store/images",
                validators=[store.validators.validate_image_size],
            ),
        ),
    ]
