# Generated by Django 4.1.7 on 2023-04-23 14:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0021_cart_customer_alter_productimage__image"),
    ]

    operations = [
        migrations.AlterModelOptions(
                name="address",
                options={"verbose_name_plural": "Addresses"},
        ),
        migrations.AlterModelOptions(
                name="cart",
                options={"ordering": ("-created",)},
        ),
        migrations.AlterModelOptions(
                name="category",
                options={"verbose_name_plural": "Categories"},
        ),
        migrations.AlterModelOptions(
                name="country",
                options={"verbose_name_plural": "Countries"},
        ),
        migrations.AlterModelOptions(
                name="favoriteproduct",
                options={},
        ),
        migrations.AlterModelOptions(
                name="itemlocation",
                options={"ordering": ("-created",)},
        ),
        migrations.AlterModelOptions(
                name="orderitem",
                options={"ordering": ("-created",)},
        ),
        migrations.AddField(
                model_name="cartitem",
                name="extra_price",
                field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
