# Generated by Django 4.1.7 on 2023-05-08 19:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0022_alter_address_options_alter_cart_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cartitem",
            options={"ordering": ("-created",)},
        ),
        migrations.RemoveConstraint(
            model_name="cartitem",
            name="unique_cart_product",
        ),
    ]
