# Generated by Django 4.1.7 on 2023-05-11 01:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0026_alter_cart_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="shipping_fee",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
            preserve_default=False,
        ),
    ]
