# Generated by Django 4.1.7 on 2023-05-11 01:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0027_product_shipping_fee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="shipping_fee",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=6,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
