# Generated by Django 4.1.7 on 2023-05-13 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0028_alter_product_shipping_fee"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders_address",
                to="store.address",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="shipped_out_days",
            field=models.DecimalField(decimal_places=2, default=5, max_digits=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="condition",
            field=models.CharField(
                blank=True,
                choices=[("N", "New"), ("U", "Used")],
                max_length=2,
                null=True,
            ),
        ),
    ]
