# Generated by Django 4.1.7 on 2023-05-14 18:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0029_order_address_product_shipped_out_days_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="shipped_out_days",
            field=models.IntegerField(),
        ),
    ]
