# Generated by Django 4.1.7 on 2023-05-17 17:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0030_alter_product_shipped_out_days"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="location",
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[("P", "Pending"), ("C", "Complete"), ("F", "Failed")],
                default="P",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="shipping_status",
            field=models.CharField(
                choices=[("P", "Pending"), ("S", "Shipping")], default="P", max_length=2
            ),
        ),
        migrations.DeleteModel(
            name="ItemLocation",
        ),
    ]
