# Generated by Django 4.1.7 on 2023-05-17 17:35

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0031_remove_product_location_alter_order_payment_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="location",
            field=django_countries.fields.CountryField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
