# Generated by Django 4.1.7 on 2023-05-17 21:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0032_product_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="shipping_status",
            field=models.CharField(
                choices=[("P", "Pending"), ("PS", "Processing")],
                default="P",
                max_length=2,
            ),
        ),
    ]
