# Generated by Django 4.1.7 on 2023-04-04 23:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_otp_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otp",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
