# Generated by Django 4.1.7 on 2023-04-18 20:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_otp_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="avatar",
            new_name="_avatar",
        ),
        migrations.AlterField(
            model_name="otp",
            name="expiry_date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
