# Generated by Django 4.1.7 on 2023-04-18 20:16

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_rename_avatar_user__avatar_alter_otp_expiry_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="_avatar",
            field=models.ImageField(upload_to=core.models.upload_path),
        ),
    ]
