# Generated by Django 4.1.7 on 2023-05-20 16:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_alter_otp_code_alter_otp_expired_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_modified",
            field=models.DateTimeField(
                default=None,
                editable=False,
                help_text="Indicates the date the user email was changed.",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
