# Generated by Django 4.1.7 on 2023-04-23 14:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_alter_user__avatar"),
    ]

    operations = [
        migrations.AlterModelOptions(
                name="otp",
                options={"ordering": ("-created",)},
        ),
    ]
