# Generated by Django 4.1.7 on 2023-03-13 15:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_alter_otp_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="auth_token",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
