# Generated by Django 4.1.7 on 2023-05-20 21:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_alter_token_token"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="tokens",
        ),
        migrations.AddField(
            model_name="token",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="token",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
