# Generated by Django 4.1.7 on 2023-03-26 11:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_alter_user_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otp",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 3, 26, 11, 3, 14, 847617, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="otp",
            name="updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
