# Generated by Django 4.1.7 on 2023-05-20 21:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_alter_token_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Token",
        ),
    ]
