# Generated by Django 4.1.7 on 2023-03-26 11:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_alter_otp_created_alter_otp_updated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otp",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
