# Generated by Django 4.1.7 on 2023-03-26 11:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_alter_otp_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otp",
            name="id",
            field=models.CharField(
                default=uuid.uuid4,
                editable=False,
                max_length=42,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
