# Generated by Django 4.1.9 on 2023-06-16 16:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_delete_token"),
    ]

    operations = [
        migrations.AlterField(
                model_name="otp",
                name="expiry_date",
                field=models.DateTimeField(
                        editable=False,
                        help_text="The date and time when the OTP will expire.",
                        null=True,
                ),
        ),
    ]
