CONDITION_USED = "U"
CONDITION_NEW = "N"
CONDITION_NOT_SPECIFIED = "NS"

CONDITION_CHOICES = (
    (CONDITION_NEW, "New"),
    (CONDITION_USED, "Used"),
    (CONDITION_NOT_SPECIFIED, "Not specified"),
)


NOTIFICATION_OFFER = "O"
NOTIFICATION_ACTIVITY = "A"
NOTIFICATION_FEED = "F"

NOTIFICATION_CHOICES = (
    (NOTIFICATION_OFFER, "Offer"),
    (NOTIFICATION_ACTIVITY, "Activity"),
    (NOTIFICATION_FEED, "Feed"),
)

PAYMENT_PENDING = "P"
PAYMENT_COMPLETE = "C"
PAYMENT_FAILED = "F"

PAYMENT_STATUS = (
    (PAYMENT_PENDING, "Pending"),
    (PAYMENT_COMPLETE, "Complete"),
    (PAYMENT_FAILED, "Failed"),
)

SHIPPING_STATUS_PENDING = "P"
SHIPPING_STATUS_SHIPPED = "PR"

SHIPPING_STATUS_CHOICES = (
    (SHIPPING_STATUS_PENDING, "Pending"),
    (SHIPPING_STATUS_SHIPPED, "Shipping"),
)
