CONDITION_USED = "U"
CONDITION_NEW = "N"

CONDITION_CHOICES = (
    (CONDITION_NEW, "New"),
    (CONDITION_USED, "Used"),
)

GENDER_ALL = "A"
GENDER_KIDS = "K"
GENDER_MALE = "M"
GENDER_FEMALE = "F"

GENDER_CHOICES = (
    (GENDER_ALL, "All"),
    (GENDER_KIDS, "Kids"),
    (GENDER_MALE, "Male"),
    (GENDER_FEMALE, "Female"),
)

NOTIFICATION_OFFER = "O"
NOTIFICATION_ACTIVITY = "A"
NOTIFICATION_FEED = "F"

NOTIFICATION_CHOICES = (
    (NOTIFICATION_OFFER, "Offer"),
    (NOTIFICATION_ACTIVITY, "Activity"),
    (NOTIFICATION_FEED, "Feed"),
)

PAYMENT_PENDING = "P"
PAYMENT_COMPLETE = "C"
PAYMENT_FAILED = "F"

PAYMENT_STATUS = (
    (PAYMENT_PENDING, "Pending"),
    (PAYMENT_COMPLETE, "Complete"),
    (PAYMENT_FAILED, "Failed"),
)

FIRST_STAR = 1
TWO_STARS = 2
THREE_STARS = 3
FOUR_STARS = 4
FIVE_STARS = 5

RATING_CHOICES = (
    (FIRST_STAR, "1 star"),
    (TWO_STARS, "2 stars"),
    (THREE_STARS, "3 stars"),
    (FOUR_STARS, "4 stars"),
    (FIVE_STARS, "5 stars")
)

SHIPPING_STATUS_PENDING = "P"
SHIPPING_STATUS_PROCESSING = "S"

SHIPPING_STATUS_CHOICES = (
    (SHIPPING_STATUS_PENDING, "Pending"),
    (SHIPPING_STATUS_PROCESSING, "Shipping"),
)
