version: 2.1

jobs:
  commista:
    docker:
      - image: cimg/python:3.10.1
      - image: cimg/mysql:8.0 # setting up database for testing
        environment:
          MYSQL_ROOT_PASSWORD: root_password
    steps:
      - checkout
      - run:
          name: "Upgrade pip"
          command: "pip3 install --upgrade pip"
      - run:
          name: "Install dependencies"
          command: "pip3 install -r requirements.txt"
      - run:
          name: "Wait for MySQL to be ready"
          command: "sleep 100" # Adjust the sleep duration as needed
      - run:
          name: "Run tests"
          command: "pytest"

workflows:
  commista-workflow:
    jobs:
      - commista
