version: 2.1

jobs:
  commista:
    docker:
      - image: cimg/python:3.10.1

    steps:
      - checkout
      - run:
          name: "Upgrade pip"
          command: "pip3 install --upgrade pip"
      - run:
          name: "Install dependencies"
          command: "pip3 install -r requirements.txt"
      - run:
          name: "Run tests"
          command: "pytest"

workflows:
  commista-workflow:
    jobs:
      - commista
