version: 2.1

jobs:
  commista:
    docker:
      - image: cimg/python:3.10.1
      - image: cimg/mysql:8.0
        environment:
          MYSQL_DATABASE: commista
          MYSQL_USER: s13g
          MYSQL_PASSWORD: S13G2£
          MYSQL_ROOT_PASSWORD: root_password
          MYSQL_PORT: 3306
          MYSQL_HOST: localhost
    # Add steps to the job
    steps:
      - checkout
      - run:
          name: "Upgrade pip"
          command: "pip3 install --upgrade pip"
      - run:
          name: "Install dependencies"
          command: "pip3 install -r requirements.txt"
      - run:
          name: "Run tests"
          command: "pytest"

workflows:
  commista-workflow:
    jobs:
      - commista
