# Generated by Django 4.1.7 on 2023-03-13 08:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_alter_otp_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otp",
            name="code",
            field=models.CharField(default=None, max_length=4),
        ),
    ]
